---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      component: mysql
  template:
    metadata:
      labels:
        app: mysql
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        resources:
          limits:
            memory: '256Mi'
            cpu: '500m'
          requests:
            memory: '32Mi'
            cpu: '100m'
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          subPath: "mysql"
          name: mysql-data
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-secrets
              key: WEBAPP_DB_PASSWORD
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-disk
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
