# backend service
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    component: mysql
spec:
  selector:
    app: mysql
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
