# frontent service
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    component: webapp
spec:
  selector:
    app: webapp
    component: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 81
  type: NodePort
