---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  creationTimestamp:
  labels:
    app: webapp
    component: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      component: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: webapp
        component: webapp
    spec:
      containers:
      - image: dyvantage01/webapp01:version-1.0.5
        name: webapp
        resources:
          limits:
            memory: '256Mi'
            cpu: '500m'
          requests:
            memory: '32Mi'
            cpu: '100m'
        env:
        - name: WEBAPP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-secrets
              key: WEBAPP_DB_PASSWORD
        ports:
        - containerPort: 81
        envFrom:
        - configMapRef:
            name: webapp-configmap
